/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsDate,
  ValidateNested,
  IsInt,
  IsEnum,
} from "class-validator";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";
import { Type } from "class-transformer";
import { QueueChat } from "../../queueChat/base/QueueChat";
import { QueueAnexo } from "../../queueAnexo/base/QueueAnexo";
import { EnumQueueChatMessageStatus } from "./EnumQueueChatMessageStatus";

@ObjectType()
class QueueChatMessage {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  agente!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  dadosAdicionais!: JsonValue;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dataHora!: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: () => QueueChat,
  })
  @ValidateNested()
  @Type(() => QueueChat)
  idQueueChat?: QueueChat;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  inOut!: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  mailMessageId!: number | null;

  @ApiProperty({
    required: false,
    type: () => [QueueAnexo],
  })
  @ValidateNested()
  @Type(() => QueueAnexo)
  @IsOptional()
  queueAnexosMesssage?: Array<QueueAnexo>;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  quotedMsg!: JsonValue;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  repliedIdMsg!: number | null;

  @ApiProperty({
    required: false,
    enum: EnumQueueChatMessageStatus,
  })
  @IsEnum(EnumQueueChatMessageStatus)
  @IsOptional()
  @Field(() => EnumQueueChatMessageStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  texto!: string | null;
}

export { QueueChatMessage as QueueChatMessage };
