import { InputJsonValue } from "../../types";
import { QueueChatMessageCreateNestedManyWithoutQueueChatsInput } from "./QueueChatMessageCreateNestedManyWithoutQueueChatsInput";

export type QueueChatCreateInput = {
  action?: string | null;
  assunto?: string | null;
  ativo?: boolean | null;
  dadosAdicionais?: InputJsonValue;
  dataFim?: Date | null;
  dataHoraLastMsg?: Date | null;
  dataIni?: Date | null;
  email?: string | null;
  fromAgente?: string | null;
  fromFila?: string | null;
  fromId?: string | null;
  fromMotivo?: string | null;
  fromName?: string | null;
  idCliente?: number | null;
  linkedid?: string | null;
  newstate?: boolean | null;
  paiId?: number | null;
  qtdMsg?: number | null;
  qtdMsgNaoLidas?: number | null;
  queue?: string | null;
  queueChatMessages?: QueueChatMessageCreateNestedManyWithoutQueueChatsInput;
  queueFrom?: string | null;
  queueTypeId?: number | null;
  sentido?: string | null;
  status?: "Option1" | null;
  ultimoAgente?: string | null;
};
