/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteAgenteArgs } from "./DeleteAgenteArgs";
import { AgenteFindManyArgs } from "./AgenteFindManyArgs";
import { AgenteFindUniqueArgs } from "./AgenteFindUniqueArgs";
import { Agente } from "./Agente";
import { AgenteService } from "../agente.service";
@graphql.Resolver(() => Agente)
export class AgenteResolverBase {
  constructor(protected readonly service: AgenteService) {}

  async _agentesMeta(
    @graphql.Args() args: AgenteFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Agente])
  async agentes(@graphql.Args() args: AgenteFindManyArgs): Promise<Agente[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Agente, { nullable: true })
  async agente(
    @graphql.Args() args: AgenteFindUniqueArgs
  ): Promise<Agente | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Agente)
  async deleteAgente(
    @graphql.Args() args: DeleteAgenteArgs
  ): Promise<Agente | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
